transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Sign_Extend.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/RISC_V_Multi_Cycle.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Register_File.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Register.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Mux32x1.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Mux3x1.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Mux2x1.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Memory_System.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Instr_Decoder.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Device_Select.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Decoder.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Data_Path.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Data_Memory.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Control_Unit.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Control_Signals.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/ALU_Decoder.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/ALU.v}
vlog -vlog01compat -work work +incdir+C:/Users/dacuevas/OneDrive\ -\ Intel\ Corporation/Documents/Maestria/Disenio\ de\ microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src {C:/Users/dacuevas/OneDrive - Intel Corporation/Documents/Maestria/Disenio de microprocesadores/disenio_de_microprocesadores/Quartus/Practicas/Risc_V_Multiciclo/src/Program_Memory.v}

